### ISSUE TITLE
kaldi apat fails with message  cat: write error: Broken pipe

### ISSUE THREAD

**Issue by cogmeta** [gooofy/kaldi-adapt-lm#2]
--> data/lang/phones/wdisambig.txt exists (newer prepare_lang.sh)
Checking word_boundary.int and disambig.int
--> generating a 61 word sequence
--> resulting phone sequence from L.fst corresponds to the word sequence
--> L.fst is OK
--> generating a 73 word sequence
--> resulting phone sequence from L_disambig.fst corresponds to the word sequence
--> L_disambig.fst is OK

Checking data/lang/oov.{txt, int} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 1 entry/entries in data/lang/oov.txt
--> data/lang/oov.int corresponds to data/lang/oov.txt
--> data/lang/oov.{txt, int} are OK

--> data/lang/L.fst is olabel sorted
--> data/lang/L_disambig.fst is olabel sorted
--> SUCCESS [validating lang directory data/lang]

creating G.fst...
cat: write error: Broken pipe
arpa2fst - 
LOG (arpa2fst[5.5.0-49a0]:Read():arpa-file-parser.cc:94) Reading \data\ section.
LOG (arpa2fst[5.5.0-49a0]:Read():arpa-file-parser.cc:149) Reading \1-grams: section.
LOG (arpa2fst[5.5.0-49a0]:Read():arpa-file-parser.cc:149) Reading \2-grams: section.
LOG (arpa2fst[5.5.0-49a0]:Read():arpa-file-parser.cc:149) Reading \3-grams: section.
LOG (arpa2fst[5.5.0-49a0]:Read():arpa-file-parser.cc:149) Reading \4-grams: section.
remove_oovs.pl: removed 1322833 lines.

INFO:root:/bin/bash -c "pushd work && bash model-dist.sh "mymodel" && popd"
~/ext/zamia/zamia-speech/data/models/cogmeta-insurance-en/work ~/ext/zamia/zamia-speech/data/models/cogmeta-insurance-en
kaldi-mymodel-adapt ...
cp: cannot stat 'exp/adapt/graph/HCLG.fst': No such file or directory
cp: cannot stat 'exp/adapt/graph/words.txt': No such file or directory
cp: cannot stat 'exp/adapt/graph/num_pdfs': No such file or directory
cp: cannot stat 'exp/adapt/graph/phones.txt': No such file or directory
cp: cannot stat 'exp/adapt/graph/phones/*': No such file or directory
cp: cannot stat 'exp/ivectors_test_hires/conf/ivector_extractor.conf': No such file or directory
cp: cannot stat 'exp/ivectors_test_hires/conf/online_cmvn.conf': No such file or directory
kaldi-mymodel-adapt/
kaldi-mymodel-adapt/ivectors_test_hires/
kaldi-mymodel-adapt/ivectors_test_hires/conf/
kaldi-mymodel-adapt/ivectors_test_hires/conf/splice.conf
kaldi-mymodel-adapt/conf/
kaldi-mymodel-adapt/conf/mfcc.conf

**Comment by cogmeta** [comment]
There are lots of errors of files missing in the adapationg process. I have been manually copying

**Comment by pablomainar** [comment]
Hi, having the same problem. I saw the README comment on running out of RAM. Is there a way of limiting RAM consumption? Anyway, I am using a machine with 32GB of RAM, so I'm not sure this is the problem. Could it be anything else?

**Comment by svenha** [comment]
I see this error too: `cat: write error: Broken pipe` For me, it was enough to avoid the `cat` in file `kaldiadaptlm/templates/kaldi-run-adaptation.sh`, instead of

    cat lm.arpa | utils/find_arpa_oovs.pl $lang/words.txt > $lmdir/oovs_lm.txt

just:

    utils/find_arpa_oovs.pl $lang/words.txt < lm.arpa > $lmdir/oovs_lm.txt
